export const ROUTES = {
  SPLASH: '/',
  ONBOARDING_INTRO1: '/onboarding/intro1',
  ONBOARDING_INTRO2: '/onboarding/intro2',
  ONBOARDING_LOGIN: '/onboarding/Login',
  ONBOARDING_NAME_INPUT: '/onboarding/NameInput',
  ONBOARDING_SPLASH_MESSAGE: '/onboarding/splashMessage',
  ONBOARDING_GUIDE_SCREEN1: '/onboarding/guideScreen1',
  ONBOARDING_GUIDE_SCREEN2: '/onboarding/guideScreen2',
  ONBOARDING_GUIDE_SCREEN3: '/onboarding/guideScreen3',
  ONBOARDING_GUIDE_SCREEN4: '/onboarding/guideScreen4',
  HOME: '/home',
} as const;

export const ONBOARDING_FLOW: Record<string, string> = {
  [ROUTES.ONBOARDING_INTRO1]: ROUTES.ONBOARDING_INTRO2,
  [ROUTES.ONBOARDING_INTRO2]: ROUTES.ONBOARDING_LOGIN,
  [ROUTES.ONBOARDING_LOGIN]: ROUTES.ONBOARDING_NAME_INPUT,
  [ROUTES.ONBOARDING_NAME_INPUT]: ROUTES.ONBOARDING_SPLASH_MESSAGE,
  [ROUTES.ONBOARDING_SPLASH_MESSAGE]: ROUTES.ONBOARDING_GUIDE_SCREEN1,
  [ROUTES.ONBOARDING_GUIDE_SCREEN1]: ROUTES.ONBOARDING_GUIDE_SCREEN2,
  [ROUTES.ONBOARDING_GUIDE_SCREEN2]: ROUTES.ONBOARDING_GUIDE_SCREEN3,
  [ROUTES.ONBOARDING_GUIDE_SCREEN3]: ROUTES.ONBOARDING_GUIDE_SCREEN4,
  [ROUTES.ONBOARDING_GUIDE_SCREEN4]: ROUTES.HOME,
} as const;
