export const ROUTES = {
  SPLASH: '/',
  HOME: '/home',
  ONBOARDING_NAME_INPUT: '/onboarding/NameInput',
  ONBOARDING_SPLASH_MESSAGE: '/onboarding/splashMessage',
  ONBOARDING_GUIDE_SCREEN1: '/onboarding/guideScreen1',
  ONBOARDING_GUIDE_SCREEN2: '/onboarding/guideScreen2',
  ONBOARDING_GUIDE_SCREEN3: '/onboarding/guideScreen3',
  ONBOARDING_GUIDE_SCREEN4: '/onboarding/guideScreen4',
} as const;

export const ONBOARDING_FLOW: Record<string, string> = {
  [ROUTES.HOME]: ROUTES.ONBOARDING_NAME_INPUT,
  [ROUTES.ONBOARDING_NAME_INPUT]: ROUTES.ONBOARDING_SPLASH_MESSAGE,
  [ROUTES.ONBOARDING_SPLASH_MESSAGE]: ROUTES.HOME,
  [ROUTES.ONBOARDING_GUIDE_SCREEN1]: ROUTES.ONBOARDING_GUIDE_SCREEN2,
  [ROUTES.ONBOARDING_GUIDE_SCREEN2]: ROUTES.ONBOARDING_GUIDE_SCREEN3,
  [ROUTES.ONBOARDING_GUIDE_SCREEN3]: ROUTES.ONBOARDING_GUIDE_SCREEN4,
  [ROUTES.ONBOARDING_GUIDE_SCREEN4]: ROUTES.HOME,
} as const;
